spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ENC(h8JcGp2P8YB7CqJGy5HKHQ==)
            client-secret: ENC(9ssJwrvAptqgadeIa8yIyItvkHPVrT2RALvQsKok0oMpCzv+KWIGwpmhQYoKX1Mc)
            client-authentication-method: client_secret_post
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
  application:
    name: with-me
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${management.address}
    password: ENC(eLJ/Us1GUOiQ1iRAhY4W5PouHz2RfDaiC4ctdbZx4ho=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${spring.datasource.connection.host}:${spring.datasource.connection.port}/${spring.datasource.connection.schema}?${spring.datasource.connection.option}
    username: ENC(sJwAPDpFpCpYliO8CL7vTA==)
    password: ENC(KE4rra8HZD1EcALaImpUG5IA2JzKyYm8)
    connection:
      host: ENC(P+srQ8WFc36tTDGtn8g7MVfT4ro4f2CxQB7mLt1vzk8=)
      port: ENC(e92pgEpnwJuZNdWXX4cc1g==)
      schema: with_me
      option: characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      connection-timeout: 5000
      idle-timeout: 10000
      maximum-pool-size: 30
management:
  address: ENC(PhaQ3ZLpQWvWcDJxFv5T8c43cYlhcrSqIo715MIi2f0=)
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.forestfull.*
logging:
  level:
    org.mybatis: INFO
jwt:
  secret: ENC(4tEWevQs4dtdpZ2cKOtN81KNquq0+g0G)
  interval:
    days: 7